### ISSUE TITLE
Post Installation Error : unexpected token

### ISSUE THREAD

**Issue by KudMath** [Vagr9K/gatsby-advanced-starter#3]
Something goes wrong with my installation, npm run serve is locked into 404, and gatsby develop logs : 
gatsby develop
success open and validate gatsby-config.js — 0.012 s
success copy gatsby files — 0.117 s
⠄ source and transform nodes/Users/MK/Documents/Dev/test/gatsby-node.js:8
  const { createNodeField } = boundActionCreators;
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at runAPI (/Users/MK/Documents/Dev/test/node_modules/gatsby/dist/utils/api-runner-node.js:84:20)
    at /Users/MK/Documents/Dev/test/node_modules/gatsby/dist/utils/api-runner-node.js:179:33
    at /Users/MK/Documents/Dev/test/node_modules/async/internal/map.js:27:9
    at replenish (/Users/MK/Documents/Dev/test/node_modules/async/internal/eachOfLimit.js:64:17)
    at iterateeCallback (/Users/MK/Documents/Dev/test/node_modules/async/internal/eachOfLimit.js:49:17)
    at /Users/MK/Documents/Dev/test/node_modules/async/internal/onlyOnce.js:12:16
    at /Users/MK/Documents/Dev/test/node_modules/async/internal/map.js:29:13
    at tryCatcher (/Users/MK/Documents/Dev/test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter (/Users/MK/Documents/Dev/test/node_modules/bluebird/js/release/nodeify.js:23:30)

help plz?

**Comment by KudMath** [comment]
NVM solved it, nvm solved it ;-)

**Comment by Vagr9K** [comment]
I was about to type the answer :smile: 
Old Node version with with no ES6 destructing support I suppose?

**Comment by KudMath** [comment]
Yep, old legacy project XD sorry for the bother.

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vagr9K** [comment]
No worries :+1:

**Comment by pathumathukorala** [comment]
I tried with Node v8.9.2 and v9.2.0. Getting the same error again and again when trying to compile the below code.
 
`const { edges: posts } = data.allMarkdownRemark`

Help pls!
